### ISSUE TITLE
Keycloak integration issues

### ISSUE THREAD

**Issue by PanagiotisFlorous** [stellio-hub/stellio-docs#23]
Trying to follow the Keycloak integration section of the docs I cannot run the EGM Keycloak image.

The image itself has no description on the dockerhub. Pulling the image and calling "docker run easyglobalmarket/keycloak:latest" results in a ton of errors and an unsuccesful run. It's unclear if further setup is needed or how to perform it.

Would greatly appreciate some pointers.

**Comment by bobeal** [comment]
Hi @PanagiotisFlorous,

Indeed, just realized the documentation in https://stellio.readthedocs.io/en/latest/admin/keycloak_integration.html is a bit outdated. I will update it in the coming days and will let you know when it is.

**Comment by bobeal** [comment]
Hi @PanagiotisFlorous,

I've just done a full update of the Keycloak integration page in  02b56827e8215719376bed025b4bc4f487d92fbc. Should be better now.

Let me know if you have any problem.

**Comment by PanagiotisFlorous** [comment]
Thank you @bobeal it's much better now!

Small note for sake of continuity and clarity in the section "Get token for this client" the command should say:

export ACCESS_TOKEN=$(http --form POST http://**{keycloak_ip}**:9080/realms/**{realm_name}**/protocol/openid-connect/token client_id={client_id} client_secret={client_secret} grant_type=client_credentials | jq -r .access_token)

Would also probably be worth showing where to get the client secret, since it might not be immidiately obvious that it's a keycloak generated value and not some password you can add when running the command. 

Other than that it seems well-written and easy to follow.

Cheers!

**Comment by bobeal** [comment]
Thanks for your feedback @PanagiotisFlorous!

Pushed some modifications a few seconds ago.
